- name: "Test Netbox prefix module"
  connection: local
  hosts: localhost
  gather_facts: False

  tasks:
    - name: "Create IP address within Netbox with only required information - State: Present"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 192.168.1.10/30
        state: present

    - name: "Update 192.168.1.10/30"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 192.168.1.10/30
          description: "Updated ip address"
          tags:
            - Updated
        state: present

    - name: "Delete IP - 192.168.1.10 - State: Absent"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 192.168.1.10
        state: absent

    - name: "Create IP in global VRF - 192.168.1.20/30 - State: Present"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 192.168.1.20/30
        state: present

    - name: "Create IP in global VRF - 192.168.1.20/30 - State: New"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          address: 192.168.1.20/30
        state: new

    - name: "Create new address with only prefix specified - State: new"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          prefix: 192.168.100.0/24
        state: new

    - name: Create IP address with several specified
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          family: 4
          address: 172.16.1.20/24
          vrf: Test VRF
          tenant: Test Tenant
          status: Reserved
          role: Loopback
          description: Test description
          tags:
            - Schnozzberry
        state: present

    - name: Create IP address and assign a nat_inside IP
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          family: 4
          address: 10.10.1.30/16
          vrf: Test VRF
          nat_inside:
            address: 172.16.1.20
            vrf: Test VRF
          interface:
            name: GigabitEthernet1
            device: test100

    - name: "Create IP address on GigabitEthernet2 - test100 - State: present"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          family: 4
          address: 10.10.200.30/16
          interface:
            name: GigabitEthernet2
            device: test100

    - name: "Create IP address on GigabitEthernet2 - test100 - State: new"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          family: 4
          prefix: 10.10.200.30/16
          interface:
            name: GigabitEthernet2
            device: test100
        state: new

    - name: "Create IP address on GigabitEthernet2 - test100 - State: present"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          family: 4
          prefix: 192.168.100.0/24
          interface:
            name: GigabitEthernet2
            device: test100
        state: present

    - name: "Create IP address on GigabitEthernet2 - test100 - State: new"
      netbox_ip_address:
        netbox_url: http://netbox-demo.org:32768
        netbox_token: 0123456789abcdef0123456789abcdef01234567
        data:
          family: 4
          prefix: 192.168.100.0/24
          interface:
            name: GigabitEthernet2
            device: test100
        state: new
